### PR TITLE
Add support for pip install -e

### PR DESCRIPTION
**Pull request by lgray**
Allow shutil to follow symlinks through copytree.

### CODE REVIEW

**Comment by nsmith-** [comment]
Condor doesn't follow symlinks though?
Or at least that was the case in
https://github.com/CoffeaTeam/lpcjobqueue/blob/fa5d0a110663769f1898e295cb81aafb3ed37c1c/bootstrap.sh#L23

**Comment by nsmith-** [comment]
Can you confirm that this worked? Because at least at one point it didn't appear that HTCondor would copy the symlink in `transfer_input_files`

**Comment by lgray** [comment]
No - you're right it does not. Only real directories function here.

**Comment by nsmith-** [comment]
Closing for now. It would be a nice feature but I suppose it requires some refactor. Perhaps zipping the environment and then using the `job_script_prologue` to unzip on the worker would work well enough?

**Pull request closed without merging**
